// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRNeE6CO0f9zAbNAxN3Gx6BJflizpaN0o',
    appId: '1:205110899501:web:ddd404ae210d14d02059a4',
    messagingSenderId: '205110899501',
    projectId: 'busstopsytem',
    authDomain: 'busstopsytem.firebaseapp.com',
    storageBucket: 'busstopsytem.firebasestorage.app',
    measurementId: 'G-N61JR4HGEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1SpujwPN_NAFLeAtAc5zNe52ujKzBfCI',
    appId: '1:205110899501:android:8de22b900d52ede82059a4',
    messagingSenderId: '205110899501',
    projectId: 'busstopsytem',
    storageBucket: 'busstopsytem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD0M5zl93r8ghOMeEUmvVh_TIlTBCfZQQ',
    appId: '1:205110899501:ios:22adb5a87fe524df2059a4',
    messagingSenderId: '205110899501',
    projectId: 'busstopsytem',
    storageBucket: 'busstopsytem.firebasestorage.app',
    iosBundleId: 'com.example.busManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD0M5zl93r8ghOMeEUmvVh_TIlTBCfZQQ',
    appId: '1:205110899501:ios:22adb5a87fe524df2059a4',
    messagingSenderId: '205110899501',
    projectId: 'busstopsytem',
    storageBucket: 'busstopsytem.firebasestorage.app',
    iosBundleId: 'com.example.busManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRNeE6CO0f9zAbNAxN3Gx6BJflizpaN0o',
    appId: '1:205110899501:web:338ad89641c93d9e2059a4',
    messagingSenderId: '205110899501',
    projectId: 'busstopsytem',
    authDomain: 'busstopsytem.firebaseapp.com',
    storageBucket: 'busstopsytem.firebasestorage.app',
    measurementId: 'G-DLQPZB811Z',
  );
}
